# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'test1'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: customagentpool
    steps:
    - task: Docker@2
      inputs: 
        containerRegistry: azureconnection
        command: buildAndPush      
        tags: 'demodocker$(Build.BUILDID)'